version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.7
    volumes:
      - /root/docker-compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /root/docker-compose/prometheus/alert_rules:/etc/prometheus/alert_rules
    ports:
      - 9090:9090
    networks:
      - prometheus
        #    command:
        #- '--web.enable-lifcycle'

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    networks:
      - prometheus

  cadvisor:
    container_name: cadvisor
    image: lagoudocker/cadvisor:v0.37.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    privileged: true
    networks:
      - prometheus

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.netclass.ignored-devices=^(veth.*)$$'
    ports:
      - 9100:9100
    networks:
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge
    name: prometheus
